#!/bin/bash
# Sync shared agent content from ~/.agents/ to supported agent clients.
# Idempotent. Safe to run multiple times.
#
# OpenCode and pi already auto-discover ~/.agents/skills/ and
# ~/.agents/AGENTS.md natively -- no sync needed for them.
set -euo pipefail

AGENTS_DIR="${AGENTS_DIR:-$HOME/.agents}"
CLAUDE_DIR="${CLAUDE_DIR:-$HOME/.claude}"
CODEX_DIR="${CODEX_DIR:-$HOME/.codex}"

DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        *)
            echo "Unknown argument: $arg" >&2
            exit 1
            ;;
    esac
done

created=0
updated=0
existed=0
skipped=0
dryruns=0

GENERATED_MARKER='<!-- Generated by sync.sh. Do not edit. -->'
temp_output=""

ensure_directory() {
    local path="$1" label="$2"

    if [ -d "$path" ]; then
        return
    fi
    if [ -e "$path" ] || [ -L "$path" ]; then
        printf "  ! %s exists (not a directory, skipping)\n" "$label"
        skipped=$((skipped + 1))
        return 1
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
        printf "  ~ %s create directory\n" "$label"
        dryruns=$((dryruns + 1))
        return
    fi

    mkdir -p -- "$path"
    printf "  + %s created\n" "$label"
    created=$((created + 1))
}

ensure_preserved_symlink() {
    local target="$1" link_path="$2" label="$3"

    if [ -L "$link_path" ]; then
        local current
        current="$(readlink "$link_path")"
        if [ "$current" = "$target" ]; then
            printf "  = %s -> %s\n" "$label" "$current"
            existed=$((existed + 1))
        else
            printf "  ! %s -> %s (unmanaged symlink, skipping)\n" "$label" "$current"
            skipped=$((skipped + 1))
        fi
        return
    fi
    if [ -e "$link_path" ]; then
        printf "  ! %s exists (not a symlink, skipping)\n" "$label"
        skipped=$((skipped + 1))
        return
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
        printf "  ~ %s -> %s\n" "$label" "$target"
        dryruns=$((dryruns + 1))
    else
        ln -s "$target" "$link_path"
        printf "  + %s -> %s\n" "$label" "$target"
        created=$((created + 1))
    fi
}

sync_codex_agents() {
    local agents_path="$CODEX_DIR/agents"
    local source

    if ! ensure_directory "$CODEX_DIR" "Codex config directory"; then
        return
    fi
    if ! ensure_directory "$agents_path" "Codex agents directory"; then
        return
    fi

    for source in "$AGENTS_DIR"/codex/agents/*.toml; do
        if [ ! -f "$source" ]; then
            printf "  ! Codex agent sources missing: %s/codex/agents/*.toml\n" "$AGENTS_DIR"
            return 1
        fi
        ensure_preserved_symlink "$source" "$agents_path/$(basename "$source")" "$(basename "$source")"
    done
}

cleanup_temp() {
    if [ -n "$temp_output" ]; then
        rm -f -- "$temp_output"
    fi
}
trap cleanup_temp EXIT

sync_claude_instructions() {
    local source="$1"
    local output="$2"
    local label="$3"
    local action="create"

    if [ ! -f "$source" ]; then
        printf "  ! %s source missing: %s\n" "$label" "$source"
        return 1
    fi

    if [ -L "$output" ]; then
        local current
        current="$(readlink "$output")"
        if [ "$current" != "$source" ]; then
            printf "  ! %s -> %s (unmanaged symlink, skipping)\n" "$label" "$current"
            skipped=$((skipped + 1))
            return
        fi
        action="migrate"
    elif [ -e "$output" ]; then
        if [ ! -f "$output" ] || [ "$(head -n 1 "$output")" != "$GENERATED_MARKER" ]; then
            printf "  ! %s exists (not generated by sync.sh, skipping)\n" "$label"
            skipped=$((skipped + 1))
            return
        fi
        action="update"
    fi

    if [ "$DRY_RUN" -eq 1 ]; then
        printf "  ~ %s <= %s (%s)\n" "$label" "$source" "$action"
        dryruns=$((dryruns + 1))
        return
    fi

    temp_output="$(mktemp "$CLAUDE_DIR/.CLAUDE.md.XXXXXX")"
    if ! {
        printf '%s\n' "$GENERATED_MARKER"
        sed 's/AGENTS\.md/CLAUDE.md/g' "$source"
    } > "$temp_output"; then
        rm -f -- "$temp_output"
        temp_output=""
        return 1
    fi

    if [ "$action" = "update" ] && cmp -s "$temp_output" "$output"; then
        rm -f -- "$temp_output"
        temp_output=""
        printf "  = %s generated from %s\n" "$label" "$source"
        existed=$((existed + 1))
        return
    fi

    mv -f -- "$temp_output" "$output"
    temp_output=""

    if [ "$action" = "update" ]; then
        printf "  + %s updated from %s\n" "$label" "$source"
        updated=$((updated + 1))
    elif [ "$action" = "migrate" ]; then
        printf "  + %s generated from %s (replaced managed symlink)\n" "$label" "$source"
        updated=$((updated + 1))
    else
        printf "  + %s generated from %s\n" "$label" "$source"
        created=$((created + 1))
    fi
}

ensure_symlink() {
    local target="$1" link_path="$2"
    local label="$3"

    if [ -L "$link_path" ]; then
        local current
        current="$(readlink "$link_path")"
        if [ "$current" = "$target" ]; then
            printf "  = %s -> %s\n" "$label" "$current"
            existed=$((existed + 1))
            return
        fi
        if [ ! -e "$link_path" ]; then
            if [ "$DRY_RUN" -eq 1 ]; then
                printf "  ~ %s -> %s (replace broken)\n" "$label" "$target"
                dryruns=$((dryruns + 1))
            else
                rm "$link_path"
                ln -s "$target" "$link_path"
                printf "  + %s -> %s (replaced broken link)\n" "$label" "$target"
                created=$((created + 1))
            fi
            return
        fi
        printf "  ! %s -> %s (wrong target, expected %s)\n" "$label" "$current" "$target"
        skipped=$((skipped + 1))
        return
    fi

    if [ -e "$link_path" ]; then
        printf "  ! %s exists (not a symlink), skipping\n" "$label"
        skipped=$((skipped + 1))
        return
    fi

    if [ "$DRY_RUN" -eq 1 ]; then
        printf "  ~ %s -> %s\n" "$label" "$target"
        dryruns=$((dryruns + 1))
    else
        ln -s "$target" "$link_path"
        printf "  + %s -> %s\n" "$label" "$target"
        created=$((created + 1))
    fi
}

echo "Syncing Claude Code config..."

sync_claude_instructions "$AGENTS_DIR/AGENTS.md" "$CLAUDE_DIR/CLAUDE.md"      "CLAUDE.md    "
ensure_symlink "$AGENTS_DIR/skills"             "$CLAUDE_DIR/skills"         "skills       "
ensure_symlink "$AGENTS_DIR/claude/agents"      "$CLAUDE_DIR/agents"         "agents       "
ensure_symlink "$AGENTS_DIR/claude/settings.json" "$CLAUDE_DIR/settings.json" "settings.json"

echo ""
echo "Syncing Codex config..."

sync_codex_agents

echo ""
if [ "$DRY_RUN" -eq 1 ]; then
    echo "Dry run: no filesystem changes made."
fi
echo "Done: $created created, $updated updated, $existed unchanged, $skipped skipped, $dryruns dry-run."
