#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TEST_ROOT="$(mktemp -d)"
GENERATED_MARKER='<!-- Generated by sync.sh. Do not edit. -->'

cleanup() {
    rm -rf -- "$TEST_ROOT"
}
trap cleanup EXIT

fail() {
    echo "FAIL: $1" >&2
    exit 1
}

run_sync() {
    local agents_dir="$1"
    local claude_dir="$2"
    shift 2
    AGENTS_DIR="$agents_dir" CLAUDE_DIR="$claude_dir" \
        bash "$REPO_DIR/sync.sh" "$@"
}

assert_generated() {
    local output="$1"
    [ -f "$output" ] || fail "$output was not created"
    [ ! -L "$output" ] || fail "$output is still a symlink"
    [ "$(head -n 1 "$output")" = "$GENERATED_MARKER" ] || \
        fail "$output has no generated marker"
    grep -Fq 'CLAUDE.md' "$output" || fail "$output has no CLAUDE.md reference"
    if grep -Fq 'AGENTS.md' "$output"; then
        fail "$output still has an AGENTS.md reference"
    fi
}

agents_dir="$TEST_ROOT/agents"
claude_dir="$TEST_ROOT/claude"
mkdir -p "$agents_dir" "$claude_dir"
printf '# Rules\nLoad AGENTS.md and nested AGENTS.md.\n' > "$agents_dir/AGENTS.md"

run_sync "$agents_dir" "$claude_dir" > "$TEST_ROOT/create.out"
assert_generated "$claude_dir/CLAUDE.md"

run_sync "$agents_dir" "$claude_dir" > "$TEST_ROOT/repeat.out"
grep -Fq '= CLAUDE.md' "$TEST_ROOT/repeat.out" || fail 'repeat sync was not unchanged'

printf '# Updated\nLoad AGENTS.md.\n' > "$agents_dir/AGENTS.md"
run_sync "$agents_dir" "$claude_dir" > "$TEST_ROOT/update.out"
grep -Fq '# Updated' "$claude_dir/CLAUDE.md" || fail 'generated file was not updated'
assert_generated "$claude_dir/CLAUDE.md"

cp "$claude_dir/CLAUDE.md" "$TEST_ROOT/before-dry-run"
printf '# Dry run must not copy AGENTS.md.\n' > "$agents_dir/AGENTS.md"
run_sync "$agents_dir" "$claude_dir" --dry-run > "$TEST_ROOT/dry-run.out"
cmp -s "$TEST_ROOT/before-dry-run" "$claude_dir/CLAUDE.md" || \
    fail 'dry-run changed CLAUDE.md'

dry_create_dir="$TEST_ROOT/dry-create"
mkdir -p "$dry_create_dir"
run_sync "$agents_dir" "$dry_create_dir" --dry-run > "$TEST_ROOT/dry-create.out"
[ ! -e "$dry_create_dir/CLAUDE.md" ] || fail 'dry-run created CLAUDE.md'

dry_migration_dir="$TEST_ROOT/dry-migration"
mkdir -p "$dry_migration_dir"
ln -s "$agents_dir/AGENTS.md" "$dry_migration_dir/CLAUDE.md"
run_sync "$agents_dir" "$dry_migration_dir" --dry-run > "$TEST_ROOT/dry-migration.out"
[ -L "$dry_migration_dir/CLAUDE.md" ] || fail 'dry-run replaced managed symlink'
[ "$(readlink "$dry_migration_dir/CLAUDE.md")" = "$agents_dir/AGENTS.md" ] || \
    fail 'dry-run changed managed symlink target'

migration_dir="$TEST_ROOT/migration"
mkdir -p "$migration_dir"
ln -s "$agents_dir/AGENTS.md" "$migration_dir/CLAUDE.md"
run_sync "$agents_dir" "$migration_dir" > "$TEST_ROOT/migration.out"
assert_generated "$migration_dir/CLAUDE.md"

unmanaged_dir="$TEST_ROOT/unmanaged"
mkdir -p "$unmanaged_dir"
printf 'user-owned Claude instructions\n' > "$unmanaged_dir/CLAUDE.md"
cp "$unmanaged_dir/CLAUDE.md" "$TEST_ROOT/unmanaged-before"
run_sync "$agents_dir" "$unmanaged_dir" > "$TEST_ROOT/unmanaged.out"
cmp -s "$TEST_ROOT/unmanaged-before" "$unmanaged_dir/CLAUDE.md" || \
    fail 'sync overwrote unmanaged CLAUDE.md'

unmanaged_link_dir="$TEST_ROOT/unmanaged-link"
mkdir -p "$unmanaged_link_dir"
printf 'other instructions\n' > "$TEST_ROOT/other-CLAUDE.md"
ln -s "$TEST_ROOT/other-CLAUDE.md" "$unmanaged_link_dir/CLAUDE.md"
run_sync "$agents_dir" "$unmanaged_link_dir" > "$TEST_ROOT/unmanaged-link.out"
[ "$(readlink "$unmanaged_link_dir/CLAUDE.md")" = "$TEST_ROOT/other-CLAUDE.md" ] || \
    fail 'sync replaced unmanaged CLAUDE.md symlink'

broken_link_dir="$TEST_ROOT/broken-link"
mkdir -p "$broken_link_dir"
ln -s "$TEST_ROOT/missing-CLAUDE.md" "$broken_link_dir/CLAUDE.md"
run_sync "$agents_dir" "$broken_link_dir" > "$TEST_ROOT/broken-link.out"
[ "$(readlink "$broken_link_dir/CLAUDE.md")" = "$TEST_ROOT/missing-CLAUDE.md" ] || \
    fail 'sync replaced broken unmanaged CLAUDE.md symlink'

directory_dir="$TEST_ROOT/directory"
mkdir -p "$directory_dir/CLAUDE.md"
run_sync "$agents_dir" "$directory_dir" > "$TEST_ROOT/directory.out"
[ -d "$directory_dir/CLAUDE.md" ] || fail 'sync replaced CLAUDE.md directory'

echo 'sync integration tests passed'
